using System.Collections.Generic;
using MicroORM.Interception;
using MicroORM.Logging;

namespace MicroORM.Configuration
{
    /// <summary>
    /// Contract for interactions and extensibility for the current configuration of the factory generated sessions.
    /// </summary>
    public interface IEnvironmentSettings
    {
        /// <summary>
        /// Gets the set of entity interceptors used for custom actions for persistence.
        /// </summary>
        HashSet<IInterceptor> Interceptors { get; }

        /// <summary>
        /// Gets  the logger for messages generated by the ORM
        /// </summary>
        ILogger Logger { get; }
    }
}